import google.generativeai as genai
from typing import List, Dict, Any, Optional
import json
import base64
from PIL import Image
import io
from app.core.config import settings

class GeminiService:
    def __init__(self):
        genai.configure(api_key=settings.GEMINI_API_KEY)
        self.model = genai.GenerativeModel('gemini-pro')
        try:
            self.vision_model = genai.GenerativeModel('gemini-pro-vision')
        except:
            self.vision_model = None
    
    async def generate_audit_report(self, audit_data: Dict[str, Any]) -> Dict[str, Any]:
        """Generate comprehensive audit report using Gemini AI"""
        
        prompt = f"""
        You are an expert hotel audit analyst. Generate a comprehensive audit report based on the following data:
        
        Property: {audit_data.get('property_name', 'Unknown')}
        Location: {audit_data.get('location', 'Unknown')}
        Audit Date: {audit_data.get('audit_date', 'Unknown')}
        Audit Type: {audit_data.get('audit_type', 'Standard')}
        
        Audit Items Data:
        {json.dumps(audit_data.get('audit_items', []), indent=2)}
        
        Please provide:
        1. Executive Summary (2-3 sentences)
        2. Key Findings (list of most important issues)
        3. Recommendations (actionable steps for improvement)
        4. Compliance Overview (summary of compliance status by section)
        5. AI Insights (patterns and trends observed)
        
        Format your response as JSON with these exact keys:
        - summary
        - key_findings (array)
        - recommendations (array)
        - compliance_overview (object)
        - ai_insights (object)
        """
        
        try:
            response = self.model.generate_content(prompt)
            
            # Try to parse as JSON, fallback to structured text
            try:
                return json.loads(response.text)
            except json.JSONDecodeError:
                return {
                    "summary": "AI-generated audit report based on collected data.",
                    "key_findings": ["Analysis completed using Gemini AI"],
                    "recommendations": ["Implement suggested improvements"],
                    "compliance_overview": {"overall": "Analysis pending"},
                    "ai_insights": {"status": "Generated by Gemini AI", "raw_response": response.text}
                }
                
        except Exception as e:
            return {
                "summary": f"Error generating report: {str(e)}",
                "key_findings": ["Unable to generate AI analysis"],
                "recommendations": ["Manual review recommended"],
                "compliance_overview": {"error": True},
                "ai_insights": {"error": str(e)}
            }
    
    async def analyze_audit_photo(self, image_data: str, context: str) -> Dict[str, Any]:
        """Analyze audit photo using Gemini Vision"""
        
        if not self.vision_model:
            return {
                "compliance_status": "unknown",
                "confidence_score": 0.0,
                "observations": ["Vision model not available"],
                "suggestions": ["Manual review required"],
                "ai_score": None
            }
        
        try:
            # Decode base64 image
            image_bytes = base64.b64decode(image_data)
            image = Image.open(io.BytesIO(image_bytes))
            
            prompt = f"""
            Analyze this hotel audit photo in the context of: {context}
            
            Please assess:
            1. Compliance status (compliant/non-compliant/partial)
            2. Confidence level (0-1)
            3. Key observations
            4. Improvement suggestions
            5. Suggested compliance score (0-100)
            
            Respond in JSON format with keys: compliance_status, confidence_score, observations, suggestions, ai_score
            """
            
            response = self.vision_model.generate_content([prompt, image])
            
            try:
                return json.loads(response.text)
            except json.JSONDecodeError:
                return {
                    "compliance_status": "unknown",
                    "confidence_score": 0.8,
                    "observations": [response.text[:200] + "..."],
                    "suggestions": ["Review AI analysis"],
                    "ai_score": 75.0
                }
                
        except Exception as e:
            return {
                "compliance_status": "error",
                "confidence_score": 0.0,
                "observations": [f"Analysis error: {str(e)}"],
                "suggestions": ["Manual review required"],
                "ai_score": None
            }
    
    async def suggest_audit_score(self, item_description: str, observations: str, photos: Optional[List[str]] = None) -> Dict[str, Any]:
        """Suggest audit score based on observations and optional photos"""
        
        media_context = ""
        if photos and len(photos) > 0:
            media_context = f"\nNumber of photos provided: {len(photos)}"
        
        prompt = f"""
        As a hotel audit expert, suggest a compliance score for this audit item:
        
        Item: {item_description}
        Observations: {observations}{media_context}
        
        Provide:
        1. Suggested score (0-100)
        2. Confidence level (0-1)
        3. Reasoning for the score
        4. Compliance zone (green: 80-100, amber: 60-79, red: 0-59)
        
        Respond in JSON format with keys: suggested_score, confidence, reasoning, compliance_zone
        """
        
        try:
            response = self.model.generate_content(prompt)
            
            try:
                result = json.loads(response.text)
                return result
            except json.JSONDecodeError:
                return {
                    "suggested_score": 75.0,
                    "confidence": 0.7,
                    "reasoning": response.text[:200] + "...",
                    "compliance_zone": "amber"
                }
                
        except Exception as e:
            return {
                "suggested_score": 50.0,
                "confidence": 0.0,
                "reasoning": f"Error: {str(e)}",
                "compliance_zone": "red"
            }

    async def analyze_individual_item(self, item: Dict[str, Any], checklist_details: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """Analyze an individual audit item and return a score (0-5) and detailed analysis.
        
        This replicates the Node.js analyzeIndividualItem behavior from geminiScoring.ts.
        """
        category = item.get("category", "General")
        item_name = item.get("item", "Unknown item")
        comments = item.get("comments", "") or ""
        status = item.get("status", "Not completed")
        photos = item.get("photos", None)
        
        # Parse photos if they are a JSON string
        media_items = []
        if photos:
            if isinstance(photos, str):
                try:
                    parsed = json.loads(photos)
                    if isinstance(parsed, list):
                        media_items = parsed
                except (json.JSONDecodeError, TypeError):
                    pass
            elif isinstance(photos, list):
                media_items = photos
        
        photo_count = sum(1 for m in media_items if m.get("type") == "photo")
        video_count = sum(1 for m in media_items if m.get("type") == "video")
        text_count = sum(1 for m in media_items if m.get("type") == "text")
        
        media_context = f"Evidence provided: {photo_count} photos, {video_count} videos, {text_count} text notes"
        if not media_items:
            media_context = "No evidence provided"
        
        system_prompt = """You are an expert hotel brand audit analyst. Analyze this specific audit checklist item and provide a score (0-5) and detailed analysis.

SCORING CRITERIA:
- 5: Excellent - Exceeds brand standards, no issues identified
- 4: Good - Meets brand standards with minor suggestions for improvement
- 3: Satisfactory - Meets basic requirements but has room for improvement
- 2: Below Standard - Notable issues that need attention
- 1: Poor - Significant problems requiring immediate action
- 0: Critical Failure - Does not meet minimum standards, major compliance issues

Analyze the auditor's comments AND any visual evidence (photos/videos) provided. When analyzing images, look for:
- Cleanliness and hygiene standards
- Brand compliance (logos, colors, signage)
- Operational efficiency and organization
- Safety and maintenance issues
- Overall quality and presentation"""

        details_text = ""
        if checklist_details:
            details_text = f"""
Checklist Details:
- Description: {checklist_details.get('description', 'N/A')}
- Weight: {checklist_details.get('weight', 'Standard')}
- Max Score: {checklist_details.get('maxScore', 5)}
"""
        
        # Build text content from media items
        text_content = ""
        text_items = [m for m in media_items if m.get("type") == "text" and m.get("content")]
        if text_items:
            text_content = "\n\nText Evidence:\n" + "\n".join(f'Text note: "{m.get("content", "")}"' for m in text_items)
        
        prompt = f"""Analyze this hotel audit checklist item:

Category: {category}
Item: {item_name}
Auditor Comments: {comments or 'No comments provided'}
Current Status: {status}
{details_text}
{media_context}{text_content}

Please provide a JSON response with:
{{
  "score": number (0-5),
  "aiAnalysis": "Detailed analysis explaining the score based on auditor comments and visual evidence. Include specific observations about what you see in photos/videos and provide actionable recommendations."
}}"""

        try:
            response = self.model.generate_content(prompt)
            
            if response.text:
                analysis = json.loads(response.text)
                score = max(0, min(5, round(analysis.get("score", 3))))
                return {
                    "score": score,
                    "aiAnalysis": analysis.get("aiAnalysis", "Analysis completed.")
                }
            else:
                raise ValueError("Empty response from AI model")
                
        except Exception as e:
            # Fallback scoring
            return self._fallback_item_analysis(item)
    
    def _fallback_item_analysis(self, item: Dict[str, Any]) -> Dict[str, Any]:
        """Fallback scoring when AI is unavailable."""
        comments = (item.get("comments", "") or "").lower()
        score = 3
        analysis = "Analysis completed using fallback scoring. "
        
        if comments:
            if any(w in comments for w in ["excellent", "perfect", "outstanding"]):
                score = 5
                analysis += "Positive feedback indicates excellent performance. "
            elif any(w in comments for w in ["good", "satisfactory", "meets"]):
                score = 4
                analysis += "Comments indicate good compliance with standards. "
            elif any(w in comments for w in ["issue", "problem", "needs improvement"]):
                score = 2
                analysis += "Issues identified that require attention. "
            elif any(w in comments for w in ["critical", "poor", "unacceptable"]):
                score = 1
                analysis += "Critical issues identified requiring immediate action. "
        else:
            score = 2
            analysis += "No detailed comments provided, limiting assessment accuracy. "
        
        photos = item.get("photos")
        if photos:
            analysis += "Supporting evidence provided enhances reliability of assessment. "
        
        return {
            "score": score,
            "aiAnalysis": analysis + "Recommend detailed review and follow-up to ensure compliance standards are maintained."
        }
    
    async def generate_audit_insights(self, audit: Dict[str, Any], audit_items: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Generate AI insights for an audit based on its items."""
        try:
            prompt = f"""You are an expert hotel audit analyst. Generate comprehensive findings and action plans based on audit data.

Property ID: {audit.get('property_id', 'Unknown')}
Total Audit Items: {len(audit_items)}

Observations by Category:
"""
            from collections import defaultdict
            categories = defaultdict(list)
            for it in audit_items:
                categories[it.get("category", "General")].append(it)
            
            for cat, items in categories.items():
                prompt += f"\n{cat}:\n"
                for it in items:
                    prompt += f"- {it.get('item', 'N/A')}: Score {it.get('score', 'N/A')}/5 - {it.get('comments', 'No comments')}\n"
            
            prompt += "\n\nRespond in JSON format with keys: findings, actionPlan"
            
            response = self.model.generate_content(prompt)
            if response.text:
                result = json.loads(response.text)
                return {
                    "findings": result.get("findings", "Analysis completed based on individual item scores."),
                    "actionPlan": result.get("actionPlan", "Continue monitoring and maintain current standards.")
                }
        except Exception as e:
            pass
        
        return {
            "findings": "Analysis completed based on individual item scores. AI insights temporarily unavailable.",
            "actionPlan": "Review individual item scores and address low-scoring areas. Consider re-running analysis when AI service is available."
        }

# Create global instance
gemini_service = GeminiService()
